version: '3'

services:

  redis-server:
    build: redis/
    ports:
      - "6379:6379"
    networks:
      - monit
  
  rabbitmq-server:
    build: rabbitmq/
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "sensu"
      RABBITMQ_DEFAULT_PASS: "sensu"
      RABBITMQ_DEFAULT_VHOST: "/sensu"
    networks:
      - monit
  sensu:
    build: sensu-server/
    ports:
      - "4567:4567"
      - "3000:3000"
    networks:
      - monit
    depends_on:
      - redis-server
      - rabbitmq-server

networks:

  monit:
    driver: bridge
