version: '3'

services:

  redis:
    build: redis/
    ports:
      - "6379:6379"
    networks:
      - elk
  
  rabbitmq:
    build: rabbitmq/
    ports:
      - "15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: "brabiller"
      RABBITMQ_DEFAULT_PASS: "test"
    networks:
      - elk

  elasticsearch:
    build: elasticsearch/
    ports:
      - "9200:9200"
      - "9300:9300"
    volumes:
      - /space/elasticsearch/data:/usr/share/elasticsearch/data
      - /space/elasticsearch/backup:/usr/share/elasticsearch/backup
    environment:
      ES_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk

  logstash:
    build: logstash/
    ports:
      - "5043:5043/udp"
    environment:
      LS_JAVA_OPTS: "-Xmx256m -Xms256m"
    networks:
      - elk
    depends_on:
      - elasticsearch

  kibana:
    build: kibana/
    volumes:
      - ./kibana/config:/usr/share/kibana/config
    ports:
      - "5601:5601"
    networks:
      - elk
    depends_on:
      - elasticsearch

  apache:
    build: apache/
    ports:
      - "80:80"
    volumes:
      - ./apache/html:/var/www/html
    logging:
      driver: gelf
      options:
        gelf-address: "udp://172.17.0.1:5043"
    networks:
      - elk

networks:

  elk:
    driver: bridge
