version: '3'

services:

  redis-server:
    build: redis/
    ports:
      - "6379:6379"
    networks:
      - monit
  
  rabbitmq-server:
    build: rabbitmq/
    ports:
      - "15672:15672"
      - "5672:5672"
    environment:
      RABBITMQ_DEFAULT_USER: "sensu"
      RABBITMQ_DEFAULT_PASS: "sensu"
      RABBITMQ_DEFAULT_VHOST: "/sensu"
    networks:
      - monit

  sensu-api:
    build: sensu-api/
    ports:
      - "4567:4567"
    networks:
      - monit
    depends_on:
      - redis-server
      - rabbitmq-server

  sensu-server:
    build: sensu-server/
    networks:
      - monit
    depends_on:
      - redis-server
      - rabbitmq-server
  
  sensu-client:
    build: sensu-client/
    networks:
      - monit
    depends_on:
      - rabbitmq-server
  
  uchiwa:
    build: sensu-uchiwa/
    ports:
      - "3000:3000"
    networks:
      - monit
    depends_on:
      - sensu-api

networks:

  monit:
    driver: bridge
